# docker-compose.yml (v root: BVI projekt/)
services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: bvi_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  gophish:
    build:
      context: ./gophish
    container_name: bvi_gophish
    command: ["sh", "./docker/run.sh"]
    depends_on:
      - mailhog
    environment:
      ADMIN_LISTEN_URL: "0.0.0.0:3333"
      ADMIN_USE_TLS: "false"
      PHISH_LISTEN_URL: "0.0.0.0:8080"
      PHISH_USE_TLS: "false"
    ports:
      - "3333:3333"
      - "8080:8080"
